MOBILE_RECEIVING EQU 1
MOBILE_SENDING EQU 2
MOBILE_STANDBY EQU 3

MOBILE_COMMAND_BEGIN_SESSION            EQU $10
MOBILE_COMMAND_END_SESSION              EQU $11
MOBILE_COMMAND_DIAL_TELEPHONE           EQU $12
MOBILE_COMMAND_HANG_UP_TELEPHONE        EQU $13
MOBILE_COMMAND_WAIT_FOR_TELEPHONE_CALL  EQU $14
MOBILE_COMMAND_TRANSFER_DATA            EQU $15
MOBILE_COMMAND_TELEPHONE_STATUS         EQU $17
MOBILE_COMMAND_READ_CONFIGURATION_DATA  EQU $19
MOBILE_COMMAND_WRITE_CONFIGURATION_DATA EQU $1a
MOBILE_COMMAND_TRANSFER_DATA_END        EQU $1f
MOBILE_COMMAND_ISP_LOGIN                EQU $21
MOBILE_COMMAND_ISP_LOGOUT               EQU $22
MOBILE_COMMAND_OPEN_TCP_CONNECTION      EQU $23
MOBILE_COMMAND_CLOSE_TCP_CONNECTION     EQU $24
MOBILE_COMMAND_DNS_QUERY                EQU $28

MOBILE_DEVICE_CGB                       EQU $80
MOBILE_DEVICE_AGB                       EQU $81
MOBILE_DEVICE_PDC                       EQU $88
MOBILE_DEVICE_CDMA                      EQU $89
MOBILE_DEVICE_PHS                       EQU $8a
MOBILE_DEVICE_DDI                       EQU $8b

MOBILE_ERROR_COMMAND                    EQU $6e
MOBILE_ERROR_CHECKSUM                   EQU $71

; Bytes sent by the non-communicating device.
; RECV is sent by the GameBoy, SEND by the Adapter
MOBILE_RECV_BYTE                        EQU $4b
MOBILE_SEND_BYTE                        EQU $d2
MOBILE_MAX_PACKET_SIZE                  EQU $fe
MOBILE_CONFIGURATION_SIZE               EQU $c0

MACFG_HEADER        EQU $00
MACFG_REGISTERED    EQU $02
MACFG_PRIMARY_DNS   EQU $04
MACFG_SECONDARY_DNS EQU $08
MACFG_LOGIN         EQU $0c
MACFG_EMAIL         EQU $2c
MACFG_SMTP          EQU $4a
MACFG_POP           EQU $5e
MACFG_PHONE1        EQU $76
MACFG_PHONE2        EQU $8e
MACFG_PHONE3        EQU $a6
MACFG_CHECKSUM      EQU $be

MOBILE_CONFIG_PHONE_BYTES EQU 8
MOBILE_CONFIG_LOGIN_BYTES EQU 10
MOBILE_CONFIG_IS_REGISTERED EQU $81
